### ISSUE TITLE
关于IV的问题

### ISSUE THREAD

**Issue by Kiritomo** [Leenshady/m3u8Downloader#1]
我这报错提示IV必须为16位byte，我看代码里面没有关于IV的内容

**Comment by Leenshady** [comment]
> 我这报错提示IV必须为16位byte，我看代码里面没有关于IV的内容

目前代码比较粗糙，并没有读取IV用于解密，可以提供报错的m3u8下载链接给我测试吗

**Comment by Kiritomo** [comment]
https://d22puzix29w08m.cloudfront.net/video/03e737991426d6856d109b6022a9e11c/675c44cb9861a692/ts_audio.m3u8
密钥好像需要cookie才能获取，我这边已经拿到了KJkAQPVdcHmHFfE6HiamsQ==

**Comment by Leenshady** [comment]
> https://d22puzix29w08m.cloudfront.net/video/03e737991426d6856d109b6022a9e11c/675c44cb9861a692/ts_audio.m3u8
> 密钥好像需要cookie才能获取，我这边已经拿到了KJkAQPVdcHmHFfE6HiamsQ==

我打不开这个链接，所以无法测试，代码已更新，增加了AES-128解密的IV支持，你可以去测试一下，有问题可以反馈给我，最好能提供一个能访问的链接给我测试

**Comment by Kiritomo** [comment]
额，其实这个是需要挂日本IP的代理才能访问的
